kind: pipeline
name: fmt_audit-code
type: docker
steps:
  - name: fmt code
    image: rust:latest
    commands:
      - rustup component add rustfmt
      - cargo fmt -- --check
  - name: audit-code
    image: rust:latest
    commands:
      - cargo install cargo-audit
      - cargo audit
      - cargo test

---
kind: pipeline
name: lint_coverage_test
type: docker
steps:
  - name: clippy-code
    image: rust:latest
    privileged: true
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings
  - name: lint-code
    image: rust:latest
    privileged: true
    commands:
      - cargo install cargo-tarpaulin
      - cargo tarpaulin --ignore-tests
