kind: pipeline
name: docker_stop
type: docker
steps:
  - name: ssh commands
    pull: if-not-exists
    image: appleboy/drone-ssh:latest
    settings:
      host:
        from_secret: ssh_ip
      port:
        from_secret: ssh_port
       script:
        - pwd
        - echo =======暂停容器=======
        - docker stop `docker ps -a | grep zero2prod | awk '{print $1}' `
        - echo =======暂停旧容器和镜像=======
        - docker rm -f `docker ps -a | grep springdemo | awk '{print $1}' `
        - docker rmi `docker images | grep springdemo | awk '{print $3}' `
        - echo =======删除多余信息=======
        - docker system prune
        - docker system prune --volumes
        - echo =======清理完成开始建立新镜像=======
        - cd /root/zero2prod_2023_2
        - docker build --tag zero2prod --file Dockerfile .


---
kind: pipeline
name: coverage_test
type: docker

steps:
  - name: test-code
    image: rust:latest
    privileged: true
    commands:
      - cargo test
      - cargo fmt -- --check

steps:
  - name: lint-code
    image: rust:latest
    privileged: true
    commands:
      - cargo install cargo-tarpaulin
      - cargo tarpaulin --ignore-tests



