kind: pipeline
name: docker_stop
type: docker
steps:
  - name: stop docker
    privileged: true
    image: appleboy/drone-ssh:latest
    settings:
      host:
        from_secret: ssh_ip
      username:
        from_secret: ssh_username

      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - pwd
        - echo =======暂停容器=======
        - docker stop `docker ps -a | grep zero2prod | awk '{print $1}' `
        - echo =======暂停旧容器和镜像=======
        - docker rm -f `docker ps -a | grep springdemo | awk '{print $1}' `
        - docker rmi `docker images | grep springdemo | awk '{print $3}' `
        - exit 0
        # - echo =======删除多余信息=======
        # - docker system prune -f
        # - docker system prune --volumes -f

---
kind: pipeline
name: fmt_audit-code
type: docker
steps:
  - name: fmt code
    pull: if-not-exists
    image: rust_ci:latest
    commands:
      - cargo fmt -- --check
  - name: audit-code
    pull: if-not-exists
    image: rust_ci:latest
    commands:
      # - cargo install cargo-audit
      - cargo audit
  - name: clippy-code
    pull: if-not-exists
    image: rust_ci:latest
    commands:
      - cargo clippy
  - name: test_tarpaulin-code
    privileged: true
    pull: if-not-exists
    image: rust_ci:latest
    commands:
      - cargo test
      - cargo tarpaulin --ignore-tests



---
kind: pipeline
name: docker_start
type: docker
steps:
  - name: ssh commands
    privileged: true
    image: appleboy/drone-ssh:latest
    settings:
      host:
        from_secret: ssh_ip
      username:
        from_secret: ssh_username

      password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
      script:
        - pwd
        - echo =======暂停容器=======
        - docker stop `docker ps -a | grep zero2prod | awk '{print $1}' `
        - echo =======暂停旧容器和镜像=======
        - docker rm -f `docker ps -a | grep springdemo | awk '{print $1}' `
        - docker rmi `docker images | grep springdemo | awk '{print $3}' `
        - echo =======删除多余信息=======
        - docker system prune -f
        - docker system prune --volumes -f
        - echo =======清理完成开始建立新镜像=======
        - cd /root/zero2prod_2023_2
        - echo =======更新源码=======
        - git pull
        - echo =======覆盖率测试=======
        - cargo tarpaulin --ignore-tests
        - echo =======删除debug中的内容=======
        - rm -rf /root/zero2prod_2023_2/target/debug/*
        - echo =======建立容器=======
        - docker build --tag zero2prod --file Dockerfile .
        - echo =======运行容器=======
        - docker run -d -p 8000:8000 zero2prod

