kind: pipeline
name: before_script
type: docker

steps:
  - name: before_script
    image: rust:latest
    commands:
      - rustc --version
      - cargo --version

---
kind: pipeline
name: audit-code
type: docker

steps:
  - name: audit-code
    image: rust:latest
    commands:
      - cargo install cargo-audit
      - cargo audit
      - cargo test

---
kind: pipeline
name: lint-code
type: docker
steps:
  - name: lint-code
    image: rust:latest
    commands:
      - rustup component add clippy
      - cargo clippy -- -D warnings
      - rustup component add rustfmt
      - cargo fmt -- --check
